# 📂 Repositorio de Programación II - En 2 Años Me Recibo

Este repositorio contiene los trabajos prácticos y proyectos de la materia Programación II.  
Está organizado en carpetas por lenguaje de programación y una carpeta especial para capturas de Git.

---

## 📁 Estructura de Carpetas

ProgramacionII/
│── Python/
│   ├── Leccio01/
│   │   ├── Clase01.py
│   │   └── Ejercicios01.py
│   ├── Leccion02/
│   │   ├── Clase02.py
│   │   └── Ejercicios02.py
│
│── Java/
│   ├── Leccion01/
│   │   ├── Clase01.java
│   │   └── Ejercicios01java
│   ├── Leccion02/
│   │   ├── Clase02.java
│   │   └── Ejercicios02.java
│
│── JavaScript/
│   ├── Leccion01/
│   │   ├── Clase01.js
│   │   └── Ejercicios01.js
│   ├── Leccion02/
│   │   ├── Clase02.js
│   │   └── Ejercicios02.js
│
│── gitCapture/
│   ├──  Python
│   |    ├── Clase01/
|   |    |     ├── imgCapture
│   │    ├── Clase02/
|   |    |     ├── imgCapture
│   ├──  JavaScript
│   |    ├── Clase01/
|   |    |     ├── imgCapture
│   │    ├── Clase02/
|   |    |     ├── imgCapture
│   ├──  Java
│   |    ├── Clase01/
|   |    |     ├── imgCapture
│   │    ├── Clase02/
|   |    |     ├── imgCapture
│── README.md
